-- MA Dental Supplies: run this SQL once in Supabase SQL Editor.
create extension if not exists pgcrypto;

create table if not exists public.products (
  id text primary key,
  name text not null,
  slug text not null unique,
  brand text default '',
  category text not null default 'المواد',
  price numeric(20,2) not null default 0,
  stock integer not null default 0,
  rating numeric(3,2) not null default 5,
  icon text default '🦷',
  image_url text default '',
  description text default '',
  featured boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.products add column if not exists image_url text default '';
create table if not exists public.orders (
  id text primary key,
  created_at timestamptz not null default now(),
  status text not null default 'جديد',
  customer_name text not null,
  customer_phone text not null,
  customer_location text not null,
  notes text default '',
  total numeric(20,2) not null default 0
);
create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id text not null references public.orders(id) on delete cascade,
  product_id text not null,
  product_name text not null,
  price numeric(20,2) not null,
  qty integer not null check (qty > 0)
);

alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

drop policy if exists "Public can read products" on public.products;
create policy "Public can read products" on public.products for select using (true);
drop policy if exists "Admins can insert products" on public.products;
create policy "Admins can insert products" on public.products for insert to authenticated with check (true);
drop policy if exists "Admins can update products" on public.products;
create policy "Admins can update products" on public.products for update to authenticated using (true) with check (true);
drop policy if exists "Admins can delete products" on public.products;
create policy "Admins can delete products" on public.products for delete to authenticated using (true);

drop policy if exists "Admins can read orders" on public.orders;
create policy "Admins can read orders" on public.orders for select to authenticated using (true);
drop policy if exists "Admins can update orders" on public.orders;
create policy "Admins can update orders" on public.orders for update to authenticated using (true) with check (true);

drop policy if exists "Admins can delete orders" on public.orders;
create policy "Admins can delete orders" on public.orders for delete to authenticated using (true);
drop policy if exists "Admins can read order items" on public.order_items;
create policy "Admins can read order items" on public.order_items for select to authenticated using (true);

create or replace function public.create_order(
  p_customer_name text,
  p_customer_phone text,
  p_customer_location text,
  p_notes text,
  p_items jsonb
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_item jsonb;
  v_product products%rowtype;
  v_qty integer;
  v_total numeric := 0;
  v_next integer;
  v_id text;
  v_items jsonb := '[]'::jsonb;
begin
  if nullif(trim(p_customer_name),'') is null
     or nullif(trim(p_customer_phone),'') is null then
    raise exception 'الاسم ورقم الهاتف مطلوبان';
  end if;

  if p_customer_location not in ('جامعة دمشق','البرامكة') then
    raise exception 'مكان الاستلام غير صالح';
  end if;

  if p_items is null
     or jsonb_typeof(p_items) <> 'array'
     or jsonb_array_length(p_items) = 0 then
    raise exception 'السلة فارغة';
  end if;

  -- رقم طلب متسلسل يبدأ من 1 وآمن من التعارض بدون الاعتماد على pgcrypto/gen_random_bytes.
  -- القفل يمنع طلبين متزامنين من الحصول على نفس الرقم.
  perform pg_advisory_xact_lock(84621531);

  select coalesce(max((substring(id from '^MA-([0-9]+)$'))::integer), 0) + 1
  into v_next
  from public.orders
  where id ~ '^MA-[0-9]+$';

  v_id := 'MA-' || v_next::text;

  -- التحقق من المنتجات والمخزون مع قفل صفوف المنتجات.
  for v_item in select * from jsonb_array_elements(p_items) loop
    v_qty := greatest(1, floor(coalesce((v_item->>'qty')::numeric,1))::int);

    select * into v_product
    from public.products
    where id = (v_item->>'id')
    for update;

    if not found then
      raise exception 'المنتج غير موجود';
    end if;

    if v_product.stock < v_qty then
      raise exception 'المخزون غير كافٍ للمنتج: %', v_product.name;
    end if;

    v_total := v_total + v_product.price * v_qty;

    v_items := v_items || jsonb_build_array(
      jsonb_build_object(
        'id', v_product.id,
        'name', v_product.name,
        'price', v_product.price,
        'qty', v_qty
      )
    );
  end loop;

  insert into public.orders(
    id, status, customer_name, customer_phone,
    customer_location, notes, total
  )
  values(
    v_id, 'جديد', trim(p_customer_name), trim(p_customer_phone),
    p_customer_location, coalesce(p_notes,''), v_total
  );

  for v_item in select * from jsonb_array_elements(v_items) loop
    insert into public.order_items(
      order_id, product_id, product_name, price, qty
    )
    values(
      v_id,
      v_item->>'id',
      v_item->>'name',
      (v_item->>'price')::numeric,
      (v_item->>'qty')::int
    );

    update public.products
    set stock = stock - (v_item->>'qty')::int,
        updated_at = now()
    where id = v_item->>'id';
  end loop;

  return jsonb_build_object(
    'id', v_id,
    'status', 'جديد',
    'total', v_total,
    'items', v_items
  );
end;
$$;

grant execute on function public.create_order(text,text,text,text,jsonb) to anon, authenticated;

-- Optional seed: app no longer seeds automatically; upload your existing data/products.json
-- through the SQL editor only if you want initial products. The website can also add them from Admin.


-- Customer-safe order tracking: requires exact order ID + phone, returns no sensitive fields beyond order details.
create or replace function public.get_order_status(
  p_order_id text,
  p_customer_phone text
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare v_order orders%rowtype; v_items jsonb;
begin
  select * into v_order from public.orders
  where id = upper(trim(p_order_id)) and regexp_replace(customer_phone, '\D', '', 'g') = regexp_replace(trim(p_customer_phone), '\D', '', 'g');
  if not found then return null; end if;
  select coalesce(jsonb_agg(jsonb_build_object('name',product_name,'price',price,'qty',qty) order by id),'[]'::jsonb) into v_items
  from public.order_items where order_id=v_order.id;
  return jsonb_build_object('id',v_order.id,'created_at',v_order.created_at,'status',v_order.status,'customer_location',v_order.customer_location,'notes',coalesce(v_order.notes,''),'total',v_order.total,'items',v_items);
end; $$;
grant execute on function public.get_order_status(text,text) to anon, authenticated;

-- Useful indexes for larger catalogs and order history.
create index if not exists products_category_idx on public.products(category);
create index if not exists products_featured_idx on public.products(featured);
create index if not exists products_created_at_idx on public.products(created_at desc);
create index if not exists orders_created_at_idx on public.orders(created_at desc);
create index if not exists orders_phone_idx on public.orders(customer_phone);

-- Product image storage: public bucket + admin-only upload/update/delete.
insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do update set public = true;

drop policy if exists "Public can view product images" on storage.objects;
create policy "Public can view product images"
on storage.objects for select
using (bucket_id = 'product-images');

drop policy if exists "Admins can upload product images" on storage.objects;
create policy "Admins can upload product images"
on storage.objects for insert to authenticated
with check (bucket_id = 'product-images');

drop policy if exists "Admins can update product images" on storage.objects;
create policy "Admins can update product images"
on storage.objects for update to authenticated
using (bucket_id = 'product-images')
with check (bucket_id = 'product-images');

drop policy if exists "Admins can delete product images" on storage.objects;
create policy "Admins can delete product images"
on storage.objects for delete to authenticated
using (bucket_id = 'product-images');

-- Performance indexes for a larger catalog (e.g. 500+ products)
create index if not exists products_brand_idx on public.products(brand);
create index if not exists products_category_created_idx on public.products(category, created_at desc);
